<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">parseRuleDetails</value>
  <value name="encodeutf8">true</value>
  <value name="body">Ly8gcGlwZWxpbmUNCgkJSURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRD
dXJzb3IoKTsNCgkJCVN0cmluZwlpbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5l
Q3Vyc29yLCAiaW5wdXQiICk7DQoJCXBpcGVsaW5lQ3Vyc29yLmRlc3Ryb3koKTsNCgkJaWYoaW5w
dXQhPW51bGwpew0KCQkNCgkJQXJyYXlMaXN0PFN0cmluZz4gcmVzdWx0TGlzdCA9IHBhcnNlUnVs
ZSggaW5wdXQsICJJbnRlcm5hbCBJRDoiKTsNCgkJIC8vIHBpcGVsaW5lDQoJCQlJRGF0YUN1cnNv
ciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29yKCk7DQoJCQkNCgkJCUlEYXRh
VXRpbC5wdXQoIHBpcGVsaW5lQ3Vyc29yXzEsICJvdXRwdXQiLHJlc3VsdExpc3QudG9BcnJheShT
dHJpbmdbXTo6bmV3KSk7DQoJCQlwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTsNCgkJfQ0KCQll
bHNlDQoJCXtJRGF0YUN1cnNvciBwaXBlbGluZUN1cnNvcl8xID0gcGlwZWxpbmUuZ2V0Q3Vyc29y
KCk7DQoJCSANCgkJSURhdGFVdGlsLnB1dCggcGlwZWxpbmVDdXJzb3JfMSwgIm91dHB1dCIsIiIp
Ow0KCQlwaXBlbGluZUN1cnNvcl8xLmRlc3Ryb3koKTt9DQoJCQkvLyBwaXBlbGluZQ0KCQkJ</value>
</Values>
