<?xml version="1.0" encoding="UTF-8"?>

<Values version="2.0">
  <value name="name">keyValuePair</value>
  <value name="encodeutf8">true</value>
  <value name="body">SURhdGFDdXJzb3IgcGlwZWxpbmVDdXJzb3IgPSBwaXBlbGluZS5nZXRDdXJzb3IoKTsNClN0cmlu
ZwlpbnB1dCA9IElEYXRhVXRpbC5nZXRTdHJpbmcoIHBpcGVsaW5lQ3Vyc29yLCAiaW5wdXQiICk7
DQpTdHJpbmcJaWQgPSBJRGF0YVV0aWwuZ2V0U3RyaW5nKCBwaXBlbGluZUN1cnNvciwgImlkIiAp
Ow0KIFN0cmluZ1tdIGtleVZhbHVlUGFpcnMgPSBpbnB1dC5zdWJzdHJpbmcoMSwgaW5wdXQubGVu
Z3RoKCkgLSAxKS5zcGxpdCgiLCAiKTsNCg0KICAgIC8vIENyZWF0ZSBhIG1hcCB0byBzdG9yZSBr
ZXktdmFsdWUgcGFpcnMNCiAgICBNYXA8U3RyaW5nLCBTdHJpbmc+IGtleVZhbHVlTWFwID0gbmV3
IEhhc2hNYXA8PigpOw0KICAgIGZvciAoU3RyaW5nIHBhaXIgOiBrZXlWYWx1ZVBhaXJzKSB7DQog
ICAgICAgIFN0cmluZ1tdIGtleVZhbHVlID0gcGFpci5zcGxpdCgiPSIpOw0KICAgICAgICBrZXlW
YWx1ZU1hcC5wdXQoa2V5VmFsdWVbMF0sIGtleVZhbHVlWzFdKTsNCiAgICB9DQoNCiAgICAvLyBH
ZXQgdGhlIHZhbHVlIGZvciB0aGUgc3BlY2lmaWVkIElEDQogICAgU3RyaW5nIHZhbHVlID0ga2V5
VmFsdWVNYXAuZ2V0KGlkKTsNCiAgICBJRGF0YVV0aWwucHV0KCBwaXBlbGluZUN1cnNvciwgIm91
dHB1dCIsIHZhbHVlICk7DQoNCiAg</value>
</Values>
